#!/usr/bin/env python3
"""Generate the KiCad footprint for a Seeed XIAO ESP32C6 soldered flat by its castellations.

Geometry (footprint frame, mm, Y down on screen): module 21.0 (X) x 17.8 (Y) per Seeed,
USB-C end at +X (its shell overhangs to X = 12.05), antenna end at -X. The 14 castellations
sit on the long edges at 2.54 mm pitch, X = +7.62 .. -7.62, on Y = +/-8.9 (the module edge);
pin 1 (D0) at (+7.62, -8.9), pins 1-7 along the -Y edge, 8-14 back along the +Y edge, so
pin 14 (5V) is at (+7.62, +8.9) — the same numbering as Seeed's socketed footprint. Pads are
1.5 x 2.5 mm centred on the edge (1.25 mm outside for the solder fillet).
Written in the KiCad 7 footprint format like the other carrier.pretty files.

Usage: gen_xiao_smd_fp.py <output .kicad_mod> [...]
"""
import sys, uuid

NAME = "Seeed_XIAO_ESP32C6_SMD"
PITCH = 2.54
EDGE_Y = 8.9
BODY_X, BODY_Y = 21.0, 17.8
PAD_W, PAD_L = 1.5, 2.5
USB_X = 12.05


def ts():
    return str(uuid.uuid4())


def f(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def line(x1, y1, x2, y2, layer, width):
    return (f'  (fp_line (start {f(x1)} {f(y1)}) (end {f(x2)} {f(y2)}) '
            f'(layer "{layer}") (width {width}) (tstamp {ts()}))')


def text(kind, s, x, y, layer, size=1.0, hide=False):
    h = " hide" if hide else ""
    return (f'  (fp_text {kind} "{s}" (at {f(x)} {f(y)} 0) (layer "{layer}"){h}\n'
            f'    (effects (font (size {size} {size}) (thickness 0.15)))\n'
            f'    (tstamp {ts()})\n  )')


out = [f'(footprint "{NAME}" (version 20221018) (generator pcbnew)', '  (layer "F.Cu")']
out.append('  (descr "Seeed Studio XIAO ESP32C6 soldered flat by its castellations: 14 SMD pads 1.5x2.5 at '
           '2.54mm pitch centred on the module edges (rows 17.8mm apart), pin 1 (D0) and pin 14 (5V) at the '
           'USB end (+X); module 21x17.8mm per Seeed, USB-C shell overhangs to X=12.05. Same pin numbering '
           'as Seeed_XIAO_2x7_Socket. Keep copper off both layers under the antenna end (-X). '
           'Generated by tools/gen_xiao_smd_fp.py.")')
out.append('  (tags "XIAO Seeed ESP32C6 castellated SMD module")')
out.append('  (attr smd)')
out.append(text("reference", "REF**", 0, -11.4, "F.SilkS"))
out.append(text("value", "XIAO ESP32C6", 0, 11.4, "F.Fab"))
out.append(text("user", "${REFERENCE}", 0, 0, "F.Fab", 0.8))
out.append(text("user", "ANTENNA", -7.5, 0, "F.Fab", 0.7))
out.append(text("user", "USB", 9.4, 0, "F.Fab", 0.7))

hx, hy, ch = BODY_X / 2, BODY_Y / 2, 1.0
# F.Fab module outline with a chamfer at the pin-1 corner (+X, -Y); USB-C shell as a box
out.append(line(-hx, -hy, hx - ch, -hy, "F.Fab", 0.1))
out.append(line(hx - ch, -hy, hx, -hy + ch, "F.Fab", 0.1))
out.append(line(hx, -hy + ch, hx, hy, "F.Fab", 0.1))
out.append(line(hx, hy, -hx, hy, "F.Fab", 0.1))
out.append(line(-hx, hy, -hx, -hy, "F.Fab", 0.1))
for y in (-4.47, 4.47):
    out.append(line(hx, y, USB_X, y, "F.Fab", 0.1))
out.append(line(USB_X, -4.47, USB_X, 4.47, "F.Fab", 0.1))

# F.SilkS: short ends only (the long edges carry the pads), plus the USB overhang and a pin-1 mark
so = 0.11
out.append(line(-hx - so, -hy - so, -hx - so, hy + so, "F.SilkS", 0.12))
out.append(line(hx + so, -4.7, USB_X + so, -4.7, "F.SilkS", 0.12))
out.append(line(hx + so, 4.7, USB_X + so, 4.7, "F.SilkS", 0.12))
out.append(line(USB_X + so, -4.7, USB_X + so, 4.7, "F.SilkS", 0.12))
out.append(line(hx + so, -hy - so, hx + so, -4.7, "F.SilkS", 0.12))
out.append(line(hx + so, 4.7, hx + so, hy + so, "F.SilkS", 0.12))
out.append(f'  (fp_poly (pts (xy 7.62 -10.55) (xy 7.32 -11.05) (xy 7.92 -11.05)) '
           f'(layer "F.SilkS") (width 0.1) (fill solid) (tstamp {ts()}))')

# F.CrtYd: module + USB overhang + pads, 0.25 mm margin
cx0, cx1, cy = -hx - 0.25, USB_X + 0.25, EDGE_Y + PAD_L / 2 + 0.25
out.append(line(cx0, -cy, cx1, -cy, "F.CrtYd", 0.05))
out.append(line(cx1, -cy, cx1, cy, "F.CrtYd", 0.05))
out.append(line(cx1, cy, cx0, cy, "F.CrtYd", 0.05))
out.append(line(cx0, cy, cx0, -cy, "F.CrtYd", 0.05))

# pads
for i in range(7):
    x = 7.62 - PITCH * i
    for num, y in ((1 + i, -EDGE_Y), (14 - i, EDGE_Y)):
        out.append(f'  (pad "{num}" smd roundrect (at {f(x)} {f(y)}) (size {f(PAD_W)} {f(PAD_L)}) '
                   f'(layers "F.Cu" "F.Paste" "F.Mask") (roundrect_rratio 0.2) (tstamp {ts()}))')

out.append('  (model "${KIPRJMOD}/carrier.3dshapes/Seeed_XIAO_ESP32C6.wrl"\n'
           '    (offset (xyz 0 0 0))\n    (scale (xyz 1 1 1))\n    (rotate (xyz 0 0 0))\n  )')
out.append(')')

body = "\n".join(out) + "\n"
for path in sys.argv[1:]:
    open(path, "w").write(body)
    print("wrote", path, len(body), "bytes")
